[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://justdial-clone.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/**/*.js", "node_modules/**/*.mjs"]